### ISSUE TITLE
IndexError executing NotSoSmartConfig

### ISSUE THREAD

**Issue by Frielyy** [ShielderSec/NotSoSmartConfig#1]
I appreciate this is somewhat niche software and support may be unlikely, but I feel like it's worth a go. It's not critical, but would help greatly with my dissertation. 

I encounter an IndexError each time I try to run NotSoSmartConfig.

Steps:
-Using Kali linux and monitor mode network card
-Capture packets in .pcap file with Wireshark
-Allow Espressif IoT device to complete SmartConfig procedure
-Place pcap in NotSoSmatConfig-master
-Execute in terminal as "sudo python3 NotSoSmartConfig.py ./<file>.pcap"

And I always encounter:

└─$ sudo python3 NotSoSmartConfig.py ./newconfig.pcap   
NotSoSmartConfig! - SmartConfig credentials decoder
Traceback (most recent call last):
  File "/home/kali/Desktop/NotSoSmartConfig-master/NotSoSmartConfig.py", line 239, in <module>
    credz = ns.decode()
  File "/home/kali/Desktop/NotSoSmartConfig-master/NotSoSmartConfig.py", line 107, in decode
    datum = self.reorder(datum)
  File "/home/kali/Desktop/NotSoSmartConfig-master/NotSoSmartConfig.py", line 194, in reorder
    current = datum[0]['dest'][-2:]
IndexError: list index out of range

Any help whatsoever appreciated. Cheers!

**Comment by TheZ3ro** [comment]
It seems that it cannot find a SmartConfig preamble in the pcap and so the datum variable is not correctly assigned.
Can you check if there are packets with lengths `515, 514, 513, 512` or `559,558,557,556` in you pcap?
Alternatively, can you share your pcap file?
Thanks

**Comment by Frielyy** [comment]
Hello, 
Apologies for the delay.

In the pcap files there are hundreds of UDP packets originating from a mobile device running Tuya Smart, allowing an Espressif IoT device to connect to the internet. The destination is always 255.255.255.255. They have all-zero payloads of different, repeating lengths. The preambles you mentioned definitely don't appear--the greatest packet length appears to be 418. I think the preamble here is 43, 45, 48, 52. 

Could the protocol have changed? I have no idea. I can send you a pcap file with the config procedure in if you have any ideas.

Thanks for your response, really appreciate it

**Comment by TheZ3ro** [comment]
Hello,
Ok that make sense on why the script is reporting the error.
I think I'll need to look into the pcap file, can you attach it here?
Thanks

**Comment by Frielyy** [comment]
Sure. I've filtered it for udp packets from the espressif device and to 255.255.255.255 only, just to be on the safe side.

Let me know if anything looks out of the ordinary. Cheers!
[smartconfig.zip](https://github.com/ShielderSec/NotSoSmartConfig/files/6941215/smartconfig.zip)

**Comment by TheZ3ro** [comment]
Thank you, I'm looking into it. Will report in the next few days

**Comment by TheZ3ro** [comment]
In the latest commit https://github.com/ShielderSec/NotSoSmartConfig/commit/c1bf1cee522abaf40ab84413fbdcdfb88af02cc3 I've made heavy code changes to better support various scenarios
Now NotSoSmartConfig supports the following protocols:
- GenericWLAN
- GenericBroadcast
- GenericMulticast (still need some polishing)
- TuyaBroadcast
- TuyaMulticast


Your PCAP has various duplicate packets (maybe you ran multiple discovery processes?) but after removing them and running the script I can recover the SSID and Password: `IOT`:`linux123`
